title: Vitalis Asiku
author: GitHub User
email: asikuvitalis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the default website for Vitalis Asiku, programmer, software architect and engineer.
  Stay tuned to get updated with the latest awesome products.

twitter_username: vitasiku1
github_username:  vitasiku

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - cv.md
 - vw.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
